### PR TITLE
fix: add flex for Carousel rendering

### LINKED ISSUE #3217: bitcoin: what is it?
when in "explore wallet" mode, going to earn/"bitcoin what is it?" leads to the a blue screen with no information

image

### PR DESCRIPTION
**Pull request by NimbleNitesh**
Fixes #3217 
Added a `flex:1` for the carousel to render properly.

### CODE REVIEW

**Comment by NimbleNitesh** [comment]
Here is a sample demo:
https://github.com/GaloyMoney/blink-mobile/assets/76262941/c40615c6-c76b-47f3-921f-81fda905991f

**Comment by nicolasburtey** [comment]
@NimbleNitesh we use conventional commits https://www.conventionalcommits.org/en/v1.0.0/

**Comment by NimbleNitesh** [comment]
I have made the changes. Can you please review it?

**Comment by nicolasburtey** [comment]
thanks for making the PR

**Pull request merged**
