### PR TITLE
feat: add Romanian translation

### PR DESCRIPTION
**Pull request by i2dor**
I've added the translated strings in Romanian.
Thank you.

### CODE REVIEW

**Review by openoms — APPROVED** [review]

**Comment by i2dor** [comment]
Thank you Openoms, köszönöm szépen!

**Comment by openoms** [comment]
@i2dor one more thing before merging. 
Can you please run in your branch:
```
yarn update-translations
```
and commit the change?

**Review by openoms — CHANGES_REQUESTED** [review]
@i2dor please merge https://github.com/i2dor/blink-mobile/pull/1 to add the necessary changes to this PR

**Review by openoms — APPROVED** [review]

**Comment by i2dor** [comment]
Thanks again Openoms, this was my first pull request. 🫡 🙏🎇

**Pull request merged**
